services:
  front:
    image: ghcr.io/c-leri/epsi-ci-cd-rpg-front:latest
    ports:
      - '3000:3000'
    environment:
      PUBLIC_BACKEND_URL: http://back:8080/api
  back:
    image: ghcr.io/c-leri/epsi-ci-cd-rpg-back:latest
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
  database:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
