name: "Back: Test"

on:
  push:
    branches:
      - main
    paths:
      - back/src/**
      - back/build.gradle
      - back/settings.gradle
      - .github/workflows/test-back.yml
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - run: chmod +x ./back/gradlew

      - name: Test
        working-directory: ./back
        run: ./gradlew test --tests "*"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: ./back/build/test-results/test/*.xml
          reporter: java-junit
